### ISSUE TITLE
I cant run on replit

### ISSUE THREAD

**Issue by Therealcodex** [pauldb09/Green-bot#124]
![Screenshot_2022-07-01-23-52-27-56](https://user-images.githubusercontent.com/102751945/176949673-e87123a5-a3cf-4452-bc56-ce30cb08c4f3.jpg)
See

**Comment by pauldb09** [comment]
Could you send a screenshot of what's there inside the directory? It seems that he can't find the index.js so you're in wrong path or you forgot to download the file

**Comment by Therealcodex** [comment]
Wait I send

**Comment by Therealcodex** [comment]
![Screenshot_2022-07-12-16-22-48-73](https://user-images.githubusercontent.com/102751945/178474304-2a91ffc7-50f6-498e-9d39-e96d22f9bb88.jpg)
![Screenshot_2022-07-12-16-22-37-29](https://user-images.githubusercontent.com/102751945/178474274-a03fa4a2-7beb-4c6c-81e4-f860923d04ba.jpg)

**Comment by Therealcodex** [comment]
If u need me to give a invite in my project i can pls send reply

**Comment by pauldb09** [comment]
You are starting the wrong file, not an issue of the bot
