### ISSUE TITLE
Invalid Package.Json

### ISSUE THREAD

**Issue by mandalapr0** [pauldb09/Green-bot#125]
Latest package.json commit broke package.json (invalid json). Need to remove last comma in dependencies.
https://github.com/pauldb09/Green-bot/commit/fc18a52822566b7351e8535147ebc44c641be00c

**Comment by pauldb09** [comment]
Yeah, fixed in [11083ac](https://github.com/pauldb09/Green-bot/commit/11083acae8330937aade40788eba3ae644257d54), thanks for reporting
