### ISSUE TITLE
Message spam

### ISSUE THREAD

**Issue by pasindu20** [pauldb09/Green-bot#146]
on green bot lot of users connect same channel and clicking the buttion (spam) it delete after but getting lot of spams so can you add it like only user can see messages when button click some users don't connect vc and use buttons it give more spams to server
add ephemeral embeds
 
itry to add it but when i do that slash command got broke i put buttonhandler.ts to `e.deferUpdate()` it brake the slash commands  functionality
can you add  ephemeral messages like only button clicked user can see it more help full (remove spams)

**Comment by pauldb09** [comment]
messages are delete after 10s so not really annoying but you could make it epheremal for you using `e.deferUpdate({epheremal: true })`

**Comment by pasindu20** [comment]
that not working if i do that buttons not working
